// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqad-pMAYTps_x7O0OW_EEIh-TVB0JeHs',
    appId: '1:24739419013:web:fe050f4f39e35f31f1aaec',
    messagingSenderId: '24739419013',
    projectId: 'proyecto2-ead5f',
    authDomain: 'proyecto2-ead5f.firebaseapp.com',
    storageBucket: 'proyecto2-ead5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmIYwiERT_S21vRpWnsx9ZZPdiwnlJGFw',
    appId: '1:24739419013:android:015fc0c08a9b4671f1aaec',
    messagingSenderId: '24739419013',
    projectId: 'proyecto2-ead5f',
    storageBucket: 'proyecto2-ead5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0UwbciNvR3SO93QGI2vkCklLxbrtYvWg',
    appId: '1:24739419013:ios:c8d488d5edd8697ef1aaec',
    messagingSenderId: '24739419013',
    projectId: 'proyecto2-ead5f',
    storageBucket: 'proyecto2-ead5f.appspot.com',
    iosClientId: '24739419013-22ob3khcokeoc0gcvl6mjgnqratc5a05.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto219400586',
  );
}
